name = "sundae/contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Experimental port of SundaeSwap to Aiken"

[repository]
user = "sundae"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "97cd61345bcc8925c521b30d0f354859eb0148cd"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "faca3e33f1cc7183e2f3801ee56b705883c6832e"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "39d4bceebeba6e02ffa72d2a2411487d97d2a738"
source = "github"
